(function(){
  'use strict';
  const $=id=>document.getElementById(id); let rows=[],currentId=null,currentFile=null,currentFileId=null,retryId=null,pendingStart=null;
  const stage={pending:'等待发送',uploading:'正在发送到本机…',processing:'正在处理音频…',queued:'等待识别',transcoding:'正在处理音频…',loading_model:'正在加载语音模型…',transcribing:'正在识别…',saving:'正在保存文字…',completed:'已完成',failed:'识别失败',cancelled:'已取消',deleted:'已删除'};
  const friendly={CONNECTOR_OFFLINE:'Helper未连接',SPEECH_MODEL_DOWNLOAD_FAILED:'模型安装失败',SPEECH_MODEL_CHECKSUM_FAILED:'模型校验失败',SPEECH_UNSUPPORTED_FORMAT:'音频格式错误',SPEECH_TRANSCODE_FAILED:'音频转码失败',SPEECH_RUNTIME_FAILED:'语音识别失败',SPEECH_RESULT_SAVE_FAILED:'文字保存失败'};
  async function api(url,options){const r=await fetch(url,{credentials:'include',...options});const b=await r.json().catch(()=>({}));if(!r.ok||b.ok===false)throw new Error(b.error||`HTTP_${r.status}`);return b}
  function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function duration(ms){if(ms===null||ms===undefined||!Number.isFinite(Number(ms)))return '—';const s=Math.round(Number(ms)/1000);return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
  function renderHistory(){ $('history').innerHTML=rows.length?rows.map(r=>`<button class="history-item ${r.id===currentId?'active':''}" data-id="${esc(r.id)}"><b>${esc(r.title||r.original_name)}</b><span>${esc(r.original_name)} · ${duration(r.duration_ms)} · ${esc(stage[r.status]||r.status)}</span><span>${new Date(r.created_at).toLocaleString()}</span></button>`).join(''):'<div class="empty">暂无会议转写</div>'; document.querySelectorAll('.history-item').forEach(b=>b.onclick=()=>openDetail(b.dataset.id)) }
  async function load(){const b=await api('/api/transcriptions');rows=b.transcriptions||[];renderHistory();if(currentId&&!rows.some(r=>r.id===currentId)){currentId=null;$('detail').classList.add('hidden')}}
  async function helper(){try{const s=await window.AIStudioSpeech.status();$('localState').textContent=`Speech Service ${s.status}${s.model?` · Model ${s.model}`:''}`;return s}catch{$('localState').textContent='Speech Service 离线';throw new Error('SPEECH_SERVICE_OFFLINE')}}
  function showError(error){const code=String(error?.message||error);$('notice').textContent=friendly[code]||({SPEECH_SERVICE_OFFLINE:'Speech Service未运行',Failed_to_fetch:'Helper未连接'}[code])||'转写失败，请稍后重试';$('notice').classList.remove('hidden')}
  function markdown(text){return esc(text||'').replace(/^### (.+)$/gm,'<h4>$1</h4>').replace(/^## (.+)$/gm,'<h3>$1</h3>').replace(/^# (.+)$/gm,'<h2>$1</h2>').replace(/^\|(.+)\|$/gm,(line)=>`<div class="md-table-row">${line.slice(1,-1).split('|').map(cell=>`<span>${cell.trim()}</span>`).join('')}</div>`).replace(/^- (.+)$/gm,'<div class="md-li">$1</div>').replace(/\n/g,'<br>')}
  async function loadMinutes(id){
    const data=await api(`/api/transcriptions/${encodeURIComponent(id)}/minutes`);const items=data.minutes||[];const active=items.find(m=>m.status==='processing'||m.status==='pending');
    $('generateMinutesBtn').disabled=!!active;
    $('minutesState').textContent=active?'正在整理会议纪要…':items.length?'可重新生成，历史版本会保留':'仅基于已完成的转写文字生成，不读取原始录音。';
    $('minutesHistory').innerHTML=items.length?items.map(m=>`<article class="minutes-version"><div class="minutes-version-head"><b>${m.status==='completed'?'已完成':m.status==='failed'?'生成失败':'处理中'}</b><span>${new Date(m.created_at).toLocaleString()} · ${esc(m.model||'')}</span></div>${m.status==='completed'?`<div class="minutes-content">${markdown(m.content_markdown)}</div>`:m.status==='failed'?`<p class="muted">${esc(m.error_code||'生成失败')} · 可重新生成</p>`:'<p class="muted">正在整理会议纪要…</p>'}</article>`).join(''):'<p class="muted">暂无会议纪要</p>';
    if(active)setTimeout(()=>{if(currentId===id)loadMinutes(id).catch(()=>{})},2000)
  }
  async function ensureModel(file,action){let s;try{s=await helper()}catch(e){showError(e);return false}if(s.status==='offline'||s.status==='error')return showError(new Error('SPEECH_SERVICE_OFFLINE')),false;if(s.model!=='ready'){currentFile=file;pendingStart=action;$('modelCard').classList.remove('hidden');$('installState').textContent=s.model==='downloading'?'正在下载模型…':'';return false}return true}
  let cancelInFlight=null, streamRetrying=false;
  async function start(file){$('notice').classList.add('hidden');if(!await ensureModel(file,()=>start(file)))return;currentFile=file;try{await window.AIStudioSpeech.upload(file,{title:$('titleInput').value,onCreated:t=>{currentId=t.id;currentFileId=t.id;showJob(t)}});await load();await openDetail(currentId)}catch(e){showError(e);if(currentId&&!cancelInFlight){cancelInFlight=window.AIStudioSpeech.cancel(currentId).catch(()=>{}).finally(()=>{cancelInFlight=null})}}}
  function showJob(t){$('jobCard').classList.remove('hidden');$('jobTitle').textContent=t.title||t.original_name;updateJob(t)}
  function updateJob(t){$('jobStatus').textContent=stage[t.status]||t.status;const active=!['completed','failed','cancelled'].includes(t.status);const uploadRatio=t.status==='uploading'&&t.byte_size?Math.max(0,Math.min(1,t.uploaded_bytes/t.byte_size)):null;const audioRatio=t.status==='transcribing'&&t.total_audio_ms?Math.max(0,Math.min(1,t.processed_audio_ms/t.total_audio_ms)):null;const realRatio=uploadRatio!==null?uploadRatio:audioRatio!==null?audioRatio:(Number.isFinite(Number(t.progress))?Math.max(0,Math.min(1,Number(t.progress))):null);const bar=$('progressBar').parentElement;bar.classList.toggle('busy',active&&realRatio===null);$('progressBar').style.width=realRatio!==null?`${realRatio*100}%`:(t.status==='completed'?'100%':'0%');$('progressText').textContent=audioRatio!==null?`${duration(t.processed_audio_ms)} / ${duration(t.total_audio_ms)} · ${t.segment_index||1}/${t.segment_count||1} 段`:realRatio!==null?`${Math.round(realRatio*100)}%`:(stage[t.status]||'');$('cancelBtn').classList.toggle('hidden',!active);if(!active)setTimeout(()=>$('jobCard').classList.add('hidden'),1000)}
  async function openDetail(id){currentId=id;renderHistory();const meta=(await api(`/api/transcriptions/${encodeURIComponent(id)}`)).transcription;if(!['completed','failed','cancelled'].includes(meta.status)){showJob(meta);$('detail').classList.add('hidden');return}$('detailTitle').textContent=meta.title||meta.original_name;$('detailMeta').textContent=`${meta.original_name} · ${duration(meta.duration_ms)} · ${new Date(meta.created_at).toLocaleString()}`;if(meta.status==='completed'){$('minutesPanel').classList.remove('hidden');const t=(await api(`/api/transcriptions/${encodeURIComponent(id)}/transcript`)).transcript;$('transcriptText').textContent=t.transcript;$('detailMeta').textContent=`${meta.original_name} · ${duration(t.duration_ms)} · ${new Date(meta.created_at).toLocaleString()}`;$('copyBtn').classList.remove('hidden');$('generateMinutesBtn').classList.remove('hidden');await loadMinutes(id)}else{$('transcriptText').textContent=meta.status==='cancelled'?'转写已取消。重新转写需要再次选择本地录音。':(friendly[meta.error_code]||'转写失败。重新选择本地录音。');$('copyBtn').classList.add('hidden');$('generateMinutesBtn').classList.add('hidden');$('minutesPanel').classList.add('hidden')}$('detail').classList.remove('hidden');$('uploadCard').classList.add('hidden')}
  $('chooseBtn').onclick=()=>{retryId=null;$('fileInput').click()};$('fileInput').onchange=()=>{const f=$('fileInput').files?.[0];if(!f)return;retryId?retry(f):start(f);$('fileInput').value=''};
  $('installBtn').onclick=async()=>{let poll;try{$('installBtn').disabled=true;$('installState').textContent='正在下载模型…';poll=setInterval(async()=>{try{const s=await window.AIStudioSpeech.status();$('installState').textContent={downloading:'正在下载模型…',verifying:'正在校验模型…',ready:'模型已就绪'}[s.model]||'正在准备模型…'}catch{}},500);await window.AIStudioSpeech.installModel();$('modelCard').classList.add('hidden');$('installState').textContent='';await helper();const action=pendingStart;pendingStart=null;if(action)await action()}catch(e){showError(e);$('installState').textContent='安装失败'}finally{clearInterval(poll);$('installBtn').disabled=false}};
  $('cancelBtn').onclick=async()=>{if(!currentId||cancelInFlight)return;cancelInFlight=window.AIStudioSpeech.cancel(currentId).catch(showError).finally(()=>{cancelInFlight=null});await cancelInFlight;await load()};
  $('copyBtn').onclick=async()=>{await navigator.clipboard.writeText($('transcriptText').textContent||'');$('copyBtn').textContent='已复制';setTimeout(()=>$('copyBtn').textContent='复制全文',1200)};
  $('generateMinutesBtn').onclick=async()=>{if(!currentId||$('generateMinutesBtn').disabled)return;$('generateMinutesBtn').disabled=true;$('minutesState').textContent='正在整理会议纪要…';try{await api(`/api/transcriptions/${encodeURIComponent(currentId)}/minutes`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:$('detailTitle').textContent})});await loadMinutes(currentId)}catch(e){showError(e);$('generateMinutesBtn').disabled=false}};
  $('retryBtn').onclick=()=>{retryId=currentId;if(currentFile&&currentFileId===currentId)retry(currentFile);else $('fileInput').click()};async function retry(file){if(!await ensureModel(file,()=>retry(file)))return;try{currentFile=file;currentFileId=retryId;await window.AIStudioSpeech.retry(retryId,file);showJob(rows.find(r=>r.id===retryId)||{id:retryId,original_name:file.name,status:'pending'});await load();await openDetail(retryId)}catch(e){showError(e)}}
  $('deleteBtn').onclick=async()=>{if(!currentId||!confirm('删除这份转写文字？'))return;await api(`/api/transcriptions/${encodeURIComponent(currentId)}`,{method:'DELETE'});currentId=null;$('detail').classList.add('hidden');$('uploadCard').classList.remove('hidden');await load()};$('refreshBtn').onclick=load;
  const events=new EventSource('/api/transcriptions/stream');events.onopen=()=>{streamRetrying=false};events.onerror=()=>{streamRetrying=true;$('localState').textContent='实时进度连接重连中…'};events.onmessage=async e=>{const u=JSON.parse(e.data);if(u.type!=='transcription_update')return;await load();const row=rows.find(r=>r.id===u.transcription_id);if(row&&row.id===currentId){Object.assign(row,u);updateJob(row);if(row.status==='completed')await openDetail(row.id)}};
  helper().catch(()=>{});load().catch(showError);
})();
